### ISSUE TITLE
getting error on [groovyx.net.http.HTTPBuilder] (http-bio-8080-exec-7:) Error parsing 'application/json; charset=utf-8' response

### ISSUE THREAD

**Issue by mithkum** [coin-worx/coin-exchange-frontend#21]
Hi @TaimoorChoudhary ,

1. I have getting this error 

2018-08-14 20:24:00,246 63529 WARN  [groovyx.net.http.HTTPBuilder] (http-bio-8080-exec-7:) Error parsing 'application/json; charset=utf-8' response
groovy.json.JsonException: A JSON payload should start with an openning curly brace '{' or an openning square bracket '['.
Instead, 'null' was found on line: 1, column: 1

on frontend please check the snapshot , and please suggest ..

2. Also please provide  me application default  user/password 

![screen shot 2018-08-15 at 2 00 18 am](https://user-images.githubusercontent.com/12783321/44116828-305d2bec-a02f-11e8-8a77-7488ed6b404f.png)

Thanks
Mithlesh

**Comment by TaimoorChoudhary** [comment]
Hi @mithkum 

Did the frontend come up or it failed after the exception? The exception looks like no data was received from the api call that was made.

Regards,
Taimoor

**Comment by mithkum** [comment]
Hi @TaimoorChoudhary ,

Frontend is comes up but not  fully page loading , you can please check attachment of frontpage,

![screen shot 2018-08-15 at 6 13 51 pm](https://user-images.githubusercontent.com/12783321/44148759-31e6f64a-a0b7-11e8-975c-e7a7048727f9.png)

Thanks

**Comment by mithkum** [comment]
Hi @TaimoorChoudhary .

I am waiting for your replay please suggest me

**Comment by TaimoorChoudhary** [comment]
Hi @mithkum 

From the screenshot attached I can see that frontend is up and loading fine. You are unable to see the charts population because there is no active data.

Regards,
Taimoor

**Comment by mithkum** [comment]
Hi @TaimoorChoudhary,

Thanks for confirm, dear can please share default admin user login and password . so that i can login the portal.

Thanks
Mithlesh

**Comment by TaimoorChoudhary** [comment]
Hi @mithkum,

If you are using the db dump file _**Front-end-initial-create-populate.sql**_ from the backend application you can login using id _**bruce**_ and pass **_pa$$word_**.

Regards,
Taimoor
