### ISSUE TITLE
install

### ISSUE THREAD

**Issue by bitcoinli** [coin-worx/coin-exchange-frontend#5]
hi,

Is there a document for installation?

**Comment by ahmadiq** [comment]
Hi @bitcoinli Thank you for your interest. Coin Exchange is an opensource project, and we are currently working on creating documentation for the installation and setup. I can get back to you once this is done.

**Comment by ghost** [comment]
up

**Comment by ahmadiq** [comment]
Hi @melmali2828 @bitcoinli we've added some details in the README. please review.
