### ISSUE TITLE
Add icon to the OHLC graph button

### ISSUE THREAD

**Issue by ahmadiq** [coin-worx/coin-exchange-frontend#9]
For the button that shows OHLC graph, please add this bar chart icon from fontawesome
https://fontawesome.com/v3.2.1/icon/bar-chart
`<i class="icon-bar-chart"></i> icon-bar-chart`

![image](https://user-images.githubusercontent.com/9255979/42800629-1e12acb2-89b6-11e8-9a69-47d03fad9ced.png)

**Comment by TaimoorChoudhary** [comment]
Changes have been made.  #15 

![chartimage](https://user-images.githubusercontent.com/4480545/42880346-654913f8-8aad-11e8-9d2d-32984cbaa8dc.png)
